services:
    app-ugc-2:
      build:
        context: src/
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      volumes:
        - ./src:/code
      env_file:
        - ./.env
      environment:
        PYTHONUNBUFFERED: 1
      networks:
        - elk_stack
        - movies_network

    nginx-ugc-2:
      image: nginx:1.19.2
      volumes:
        - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
        - /tmp/logs/nginx/:/var/log/nginx/
      depends_on:
        - app-ugc-2
      ports:
        - 8080:80
      networks:
        - elk_stack
        - movies_network

    filebeat-ugc-2:
      image: docker.elastic.co/beats/filebeat:7.3.2
      volumes:
        - /tmp/logs/nginx:/var/log/nginx:ro
        - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml
      depends_on:
        - app-ugc-2
        - nginx-ugc-2
      networks:
        - elk_stack
        - movies_network

networks:
 elk_stack:
   external: true
  movies_network:
    external: true
    name: movies_network