filebeat.inputs:
- type: log
  enabled: true
  fields:
    source: 'ugc-2'
  paths:
    - /var/log/nginx/*
  json:
    keys_under_root: true
    add_error_key: true

processors:
  - add_tags:
      tags: ['ugc-2']

output.logstash:
  enabled: true
  hosts: ["logstash-elk:5045"]